## alpha-tls-secrets.yaml
## Generate keys/certs with `dgraph cert`
## * https://dgraph.io/docs/v20.11/deploy/tls-configuration/#tls-options
##
## Create Dgraph certs/keys for Kubernetes with:
##  MYLIST=$(REPLICAS=3 RELEASE=my-release NAMESPACE=default ../scripts/get_alpha_list.sh)
##  dgraph cert --nodes localhost,$MYLIST --client backupuser
##
## Convert secrets /tls directory to secrets .yaml with
##  ../scripts/make_tls_secrets.sh
##
## NOTE: Client Certificates used for Mutual TLS with Dgraph Alpha do not need to
## be included in this file.  These client certificates are needed by clients to
## access Dgraph Alpha when tls_client_auth is set to REQUIREANDVERIFY
alpha:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
