## alpha-acl-secret.yaml
## * https://dgraph.io/docs/enterprise-features/access-control-lists/
alpha:
  acl:
    file:
      ## Demonstration Purposes Only: 12345678901234567890123456789012
      ## Note that Kubernetes secrets must be base64-encoded
      ##  Example:
      ##   echo '12345678901234567890123456789012' | tr -d '\n' | base64
      hmac_secret_file: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
