## alpha-acl-secret.yaml
## * https://dgraph.io/docs/enterprise-features/access-control-lists/
alpha:
  acl:
    file:
      # Demonstration Purposes Only: 1234567890123456789012345678901
      # Note that Kubernetes secrets must by base64-encoded
      hmac_secret_file: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMQo=
