## alpha-tls-secrets.yaml
## Generate keys/certs with `dgraph cert`
## * https://dgraph.io/docs/master/deploy/#tls-options
## Convert secrets /tls directory to secrets .yaml with 
##  ../scripts/make_tls_secrets.sh
alpha:
  tls:
    files:
      ca.crt: REDACTED
      ca.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
