## alpha-enc-config.yaml
## Specify Encryption at Rest configuration options for `dgraph alpha`
## * https://dgraph.io/docs/enterprise-features/encryption-at-rest/
alpha:
  encryption:
    enabled: true
  configFile:
    ## NOTE: lru_mb deprecated after v20.11.0 and is no longer needed
    config.toml: |
      encryption_key_file = '/dgraph/enc/enc_key_file'
      whitelist = '10.0.0.0/8,172.0.0.0/8,192.168.0.0/16'
      lru_mb = 2048
