## alpha-enc-secret.yaml
## * https://dgraph.io/docs/enterprise-features/encryption-at-rest/
alpha:
  encryption:
    file:
      ## Demonstration Purposes Only: 12345678901234567890123456789012
      ## Note that Kubernetes secrets must be base64-encoded
      ##  Example:
      ##   printf '12345678901234567890123456789012' | base64
      enc_key_file: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
