# alpha-tls-config.yaml
# Specify TLS Command line options for `dgraph alpha`
# * https://dgraph.io/docs/master/deploy/#tls-options
alpha:
  tls:
    enabled: true
  configFile:
    config.yaml: |
      tls_client_auth: VERIFYIFGIVEN
      tls_dir: /dgraph/tls
      tls_use_system_ca: true