## alpha-enc-secret.yaml
## * https://dgraph.io/docs/enterprise-features/encryption-at-rest/
alpha:
  encryption:
    file:
      # Demonstration Purposes Only: 123456789012345
      # Note that Kubernetes secrets must by base64-encoded
      enc_key_file: MTIzNDU2Nzg5MDEyMzQ1Cg==
