## backup-s3-config.yaml
## * https://dgraph.io/docs/master/enterprise-features/binary-backups/
##
## Demonstrates
## * Binary Backups to S3
## * Mutual TLS (see https://dgraph.io/docs/deploy/tls-configuration/)
## * Auth Token (see https://dgraph.io/docs/deploy/dgraph-administration/#securing-alter-operations)
backups:
  full:
    enabled: true
    schedule: "0 * * * *"
  incremental:
    enabled: true
    schedule: "0 1-23 * * *"
  admin:
    tls_client: backupuser
  ## Requires AWS S3 Bucket to be provisioned
  destination: s3://s3.<region>.amazonaws.com/<bucket>
alpha:
  acl:
    enabled: true
  configFile:
    config.hcl: |
      whitelist          = "10.0.0.0/8,172.0.0.0/8,192.168.0.0/16"
      tls_client_auth    = "REQUIREANDVERIFY"
      tls_dir            = "/dgraph/tls"
      tls_use_system_ca" = true
      auth_token         = "1234567890AbCdE"
      lru_mb             = 2048
  extraEnvs:
    ## AWS Profile for IAM User with attached policy that grants access to
    ##  S3 Bucket (demo key/secret below)
    - name: AWS_ACCESS_KEY_ID
      value: AKIAABCD3FGH1JKLMN0P
    - name: AWS_SECRET_ACCESS_KEY
      value: aBcDeFgHiJkLmNoPqRsTuVwXyZ/+0124567890Ab
