## Specify TLS configuration options for `dgraph alpha` and `dgraph zero`
## * https://dgraph.io/docs/deploy/tls-configuration/#using-tls-with-internal-and-external-ports-encrypted
## NOTE: Client Certificates used for Mutual TLS must be included, as these are
## need by Dgraph nodes to authenticate to each other.
alpha:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      client.dgraphuser.crt: REDACTED
      client.dgraphuser.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
zero:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      client.dgraphuser.crt: REDACTED
      client.dgraphuser.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
