## Specify TLS configuration options for `dgraph alpha` and `dgraph zero`
## * https://dgraph.io/docs/deploy/tls-configuration/#using-tls-with-internal-and-external-ports-encrypted
## NOTE: Client Certificates used for Mutual TLS must be configured, as these are
## need by Dgraph nodes to authenticate to each other.
global:
  domain: cluster.local

alpha:
  tls:
    enabled: true
  configFile:
    config.yaml: |
      tls:
        ca_cert: /dgraph/tls/ca.crt
        client_cert: /dgraph/tls/client.dgraphuser.crt
        client_key: /dgraph/tls/client.dgraphuser.key
        client_auth_type: REQUIREANDVERIFY
        internal_port: true
        server_cert: /dgraph/tls/node.crt
        server_key: /dgraph/tls/node.key
        use_system_ca: true
zero:
  tls:
    enabled: true
  configFile:
    config.yaml: |
      tls:
        ca_cert: /dgraph/tls/ca.crt
        client_cert: /dgraph/tls/client.dgraphuser.crt
        client_key: /dgraph/tls/client.dgraphuser.key
        client_auth_type: REQUIREANDVERIFY
        internal_port: true
        server_cert: /dgraph/tls/node.crt
        server_key: /dgraph/tls/node.key
        use_system_ca: true
