# kubernetes-ingress (NGINX ingress) with GRPC support
# --------------------------------------
# Two ingress resources will configured for mixed GPRC and HTTP support.
#
# TLS will be terminated by the ingress controller.  The ingress controller
# should be configured as an Layer 4 external load balancer.
#
# References:
# * https://github.com/nginxinc/kubernetes-ingress
# * https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#listeners
# * https://github.com/nginxinc/kubernetes-ingress/tree/v2.3.0/examples/grpc-services
# * https://cert-manager.io/

global:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - ratel.example.com
          - alpha.example.com
        secretName: http-example-tls
    ratel_hostname: ratel.example.com
    alpha_hostname: alpha.example.com
  ingress_grpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      # NOTE: http2 must be configured in configmap for NGINX ingress controller.
      # IMPORTANT: Change <RELEASE> to release name used at install, e.g. my-release
      nginx.org/grpc-services: "<RELEASE>-dgraph-alpha"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - grpc.example.com
        secretName: grpc-example-tls
    alpha_grpc_hostname: grpc.example.com
