apiVersion: v1
name: dgraph
version: 0.0.5
appVersion: v1.2.2
description: Dgraph is a horizontally scalable and distributed graph database, providing ACID transactions, consistent replication and linearizable reads.
keywords:
- dgraph
- database
- Graph
- GraphQL
- nosql
home: https://dgraph.io/
sources:
- https://charts.dgraph.io/
- https://github.com/dgraph-io/dgraph
maintainers:
- name: dgraph
  email: contact@dgraph.io
icon: https://dgraph.io/assets/images/logo.png
